### ISSUE TITLE
That's a so great work,but i have a some questions?

### ISSUE THREAD

**Issue by xzr52** [baaivision/Uni3D#1]
1.How to perform cross-modal retrieval? 
2.Do you need to download the complete data set?
3.How long does it take?
I am a beginner and asked some basic questions. I would be very grateful if you could answer me。

**Comment by mabaorui** [comment]
We appreciate your interest. 
1. For details on cross-modal retrieval, please refer to section 4.6 of this paper. 
2. You will need to prepare a complete 3D database for retrieval. 
3. Retrieval time is directly proportional to the number of 3D models in the database.

**Comment by junshengzhou** [comment]
I am closing this issue. If you have any more questions, please feel free to reopen it or create new issues. :)

**Comment by foocker** [comment]
> We appreciate your interest.
> 
>     1. For details on cross-modal retrieval, please refer to section 4.6 of this paper.
> 
>     2. You will need to prepare a complete 3D database for retrieval.
> 
>     3. Retrieval time is directly proportional to the number of 3D models in the database.

the format of the dataset must be point cloud? if mesh, we should  transform mesh to point cloud?
