### ISSUE TITLE
Code release for point cloud segmentation and painting?

### ISSUE THREAD

**Issue by JarneVdH** [baaivision/Uni3D#3]
Dear authors,

Thank you for your interesting work and your extensive experiments. 🎉 
When will the code be released for the segmentation and the painting task? 🎨 

Kind regards
Jarne

**Comment by junshengzhou** [comment]
Hi,

Thanks for your interest on our work! We are planning to release the code for more downstream tasks, but there is no strict time plan. It will most likely be after the acceptence.

Best,
Junsheng

**Comment by JarneVdH** [comment]
Hi!
Is the segmentation architecture for Uni3D based on the [PointBERT segmentation model](https://github.com/lulutang0608/Point-BERT/blob/master/segmentation/models/PointTransformer.py)?
That would already help me reproducing the results. :)
