### ISSUE TITLE
open-world understanding

### ISSUE THREAD

**Issue by rongmq8802** [baaivision/Uni3D#4]
Thank you for your excellent work. I have a question about applying a point cloud classification model trained on object datasets to 3D scene segmentation tasks like ScanNet. Does the model require fine-tuning to adapt to the complexities of full scene segmentation, or can the original model be directly applied to this task? Your insights would be very helpful. Thank you!

**Comment by junshengzhou** [comment]
Hi,

Thanks for you interest on Uni3D! We justify that the the open-world understanding task is to recognize the objects on real-scanned 3D scenes. As described in Sec.4.3, we conduct the experiment with the same settings as CLIP^2 where the ground truth
instant segmentation is available and the target is to recognize the category of each instant of the scene in a zero-shot way. So we do not perform scene segmentation on this task. 

For exploring the dense prediction ability of Uni3D, we leverage Uni3D in the open-vocabulary part segmentation with a fine-tuning by texts of unseen parts. You can refer to Sec.4.4 if you are interest in leveraging Uni3D for segmentation.

Best,
Junsheng

**Comment by junshengzhou** [comment]
I am closing this issue. If you have any more questions, please feel free to reopen it or create new issues. :)

**Comment by seanzhuh** [comment]
Is there anyone who has successfully replicate Uni3D on open-world understanding tasks? I just pass in the instance point clouds into Uni3D without requiring it to actually localize, and the result is bad, I guess it's related to the number of points within the instance, cause mine is much smaller than 10,000 points used during pretraining, typically 2K or with a maximum 5K points
