### ISSUE TITLE
Model release

### ISSUE THREAD

**Issue by KairosXu** [baaivision/Uni3D#9]
Thanks for your nice work!
Your contribution of designing billion-scale 3D representation models can be seen in Table5 in the experimental section of the paper. But I only found the Uni3d-g model with the best performance in the repo. I'm here to ask for your releasing of other scales of representation model checkpoints, e.g. Uni3d-L and Uni3d-B, so that we could ultilize all these models for further research!
I appreciate your quick response.

**Comment by Wolfwjs** [comment]
Thank you for your interest in our work! We are currently in the process of organizing and uploading the Uni3d-L and Uni3d-B models. We anticipate completing this task within the week. Please stay tuned for the updates, and we appreciate your patience!

**Comment by cshizhe** [comment]
Thanks for sharing the Uni3d-L and Uni3d-B models! Could you also release the smaller versions such as Uni3d-Ti and Uni3d-S in the paper?

**Comment by Wolfwjs** [comment]
Thank you for your interestd! Since our work focuses on exploring representational capabilities at larger scales, we currently do not have bandwidth to release the tiny and small versions. By the way, may I ask which specific areas of research you need the tiny and small models for?

**Comment by Wolfwjs** [comment]
Thank you for your interest! Since our work focuses on exploring representational capabilities at larger scales, we currently do not have bandwidth to release the tiny and small versions. By the way, may I ask which specific areas of research you need the tiny and small models for?

**Comment by Wolfwjs** [comment]
Thank you for your interest! Since our work focuses on exploring representational capabilities at larger scales, we currently do not have bandwidth to release the tiny and small versions.

**Comment by Wolfwjs** [comment]
We have already released all scale models to [Hugging Face](https://huggingface.co/BAAI/Uni3D/tree/main/modelzoo) and also updated the inference script for your reference.
